name: Daily Anime Data Update
on:
  schedule:
    - cron: '0 0 * * *'    # Runs every day at midnight
  workflow_dispatch:        # Allows manual trigger for testing

permissions:
  contents: write
  issues: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run data collection
        id: update_attempt
        continue-on-error: true
        env:
          MAL_CLIENT_ID: ${{ secrets.MAL_CLIENT_ID }}
        run: |
          python src/mal_api.py
          python src/check_missing.py
      
      - name: Check Update Status
        id: check_update
        if: steps.update_attempt.outcome == 'success'
        run: |
          if git diff --quiet data/raw/; then
            echo "status=unchanged" >> $GITHUB_OUTPUT
          else
            echo "status=changed" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit Changes
        if: steps.check_update.outputs.status == 'changed'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/raw/*.csv data/missing_data_report.txt
          git commit -m "data: Update anime data for $(date +'%Y-%m-%d')"
          git push